import type { Metadata } from "next";
import "../styles/globals.css";
import { AOSInit } from "@/lib/aos";
import Header from "@/components/header";
import GlobalModals from "@/components/global-modals";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <AOSInit />
      <body>
        <Header />
        {children}
        <Footer />

        <GlobalModals />
      </body>
    </html>
  );
}
